config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  get 'about' => 'main#about'

  resources :creatures

  resources :tags

end

app/models/creature.rb
class Creature < ActiveRecord::Base
	has_and_belongs_to_many :tags
end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :creatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

	def index
		@creatures = Creature.all
	end
	def new
		@creature = Creature.new
		@tags = Tag.all
	end
	def create
		c = Creature.create creature_params
		update_tags c
		redirect_to creatures_path
	end
	def creature_params
		params.require(:creature).permit(:name, :description)
	end
	def show
		@creature=Creature.find params[:id]
	end
	def destroy
		Creature.find(params[:id]).delete
		redirect_to creatures_path
	end
	def edit
    @creature = Creature.find params[:id]
    @tags = Tag.all
	end

	def update

	    c = Creature.find params[:id]
	    c.update creature_params
	    redirect_to creatures_path

	    c.tags.clear
    	update_tags c
	end
	def update_tags creature
    creature_tags = params[:creature][:tag_ids]
    creature_tags.each do |id|
      creature.tags << Tag.find(id) unless id.blank?
    end
  end


end

app/controllers/main_controller.rb
class MainController < ApplicationController

	def index
	end

	def about
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = Tag.all
	end
	def new
		@tag = Tag.new
	end
	def create
		Tag.create tag_params
		redirect_to tags_path
	end
	def tag_params
		params.require(:tag).permit(:name)
	end
	def show
		@tag=Tag.find params[:id]
	end
	def destroy
		t = Tag.find(params[:id])
		if t.creatures.length == 0
			t.destroy
			redirect_to tags_path
		else
		redirect_to tags_path
		end
	end
	def edit
    @tag = Tag.find params[:id]
	end

	def update
	    t = Tag.find params[:id]
	    t.update tag_params
	    redirect_to tags_path
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/creatures/edit.html.erb
<h2>DID IT MUTATE???</h2>

<%= bootstrap_form_for @creature do |f| %>
<%= f.text_area :name %>
<%= f.text_field :description %>
<%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
<%= f.primary %>
<% end %>

app/views/creatures/index.html.erb
<div class="col-sm-8 col-sm-offset-2">
<h3>The Creatures!
  <%= link_to "  Add a new creature!", new_creature_path, class: 'btn btn-primary btn-xs glyphicon glyphicon-plus pull-right' %>
</h3>

<% @creatures.each do |creature| %>
		<div class="well">
		  <h2><%= creature.name %></h2>
		  <em>Description: <%= creature.description %></em>
		  <%= link_to "", creature, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right' %>
		  <%= link_to "", edit_creature_path(creature), class: 'btn btn-primary btn-xs glyphicon glyphicon-pencil pull-right' %>
		  <%= link_to "See the creature closer!", creature, class: 'pull-right' %>
		  <p>
	  <% creature.tags.each do |tag| %>
	    <%= link_to "##{tag.name}", tag %>
	  <% end %>
	  </p>
		</div>
<% end %>
</div>

app/views/creatures/new.html.erb

<h2>Did you see a new creature?</h2>

<%= bootstrap_form_for @creature do |f| %>
<%= f.text_field :name %>
<%= f.text_area :description %>
<%= f.primary :"Add Creature" %>
<%= f.collection_check_boxes :tag_ids, @tags, :id, :name %>
<% end %>

app/views/creatures/show.html.erb
<h3>The Creature</h3>

<%= link_to "&larr; back".html_safe, creatures_path %>

<div class="well">
  <h2><%= @creature.name %></h2>
  <em>
 <%= @creature.description %>
  </em>
<%= link_to "", @creature, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right' %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogAdventure</title>

  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Freckle+Face|Slackey|Indie+Flower' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<nav class="navbar navbar-default">
	<div class="navbar-header">
 		<h1>The bog nav!</h1>
  </div>
  <div class="collapse navbar-collapse">
  <ul class="nav navbar-nav danger">
 		<li><%= link_to "Home", root_path %></li>
 		<li><%= link_to "About", about_path %></li>
 		<li><%= link_to "Creatures", creatures_path %></li>
    <li><%= link_to "Tags", tags_path %></li>
    </ul>
  </div>
</nav>
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<h1>Ahhh a nasty bog!</h1>
		</div>
</div>

<%= yield %>

</body>
</html>

app/views/main/about.html.erb
<div<div class="col-sm-8 col-sm-offset-2 mainTextArea">
	
<h2>About</h2>
<p>Ahhh! What is a bog you ask?? Well let me just tell you!</p>
<p>A bog is a mire that accumulates peat, a deposit of dead plant material—often mosses, and in a majority of cases, sphagnum moss.[1] It is one of the four main types of wetlands. Other names for bogs include mire, quagmire, and muskeg; alkaline mires are called fens. They are frequently covered in ericaceous shrubs rooted in the sphagnum moss and peat. The gradual accumulation of decayed plant material in a bog functions as a carbon sink.[2]

Bogs occur where the water at the ground surface is acidic and low in nutrients. In some cases, the water is derived entirely from precipitation, in which case they are termed ombrotrophic (rain-fed). Water flowing out of bogs has a characteristic brown colour, which comes from dissolved peat tannins. In general, the low fertility and cool climate results in relatively slow plant growth, but decay is even slower owing to the saturated soil. Hence peat accumulates. Large areas of landscape can be covered many metres deep in peat.[3][4]

Bogs have distinctive assemblages of plant and animal species, and are of high importance for biodiversity, particularly in landscapes that are otherwise settled and farmed.</p>
</div>

app/views/main/index.html.erb
<div class="col-sm-8 col-sm-offset-2">
	<h3>Welcome to the bog!</h3>
</div>
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="http://www.theweeklings.com/wp-content/uploads/Release_the_Kraken_by_GENZOMAN-reduced1.jpg">
    </div>
    <div class="item">
      <img src="http://dlisted.com/wp-content/uploads/2013/11/nicolas_cage10.jpg">
    </div>
    <div class="item">
      <img src="http://s3.amazonaws.com/rapgenius/filepicker%2FIBS0HUFAQhpegHDWs0iw_gollum.jpg">
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
	</div>

app/views/tags/index.html.erb
<h1>Look at these tags!
<%= link_to "  Add a new tag!", new_tag_path, class: 'btn btn-primary btn-xs glyphicon glyphicon-plus pull-right' %>
</h1>
<% @tags.each do |tag| %>
		<div class="well">
		  <h2><%= tag.name %></h2>
		  <%= link_to "", tag, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right' %>
		  <%= link_to "checkout this tag", tag, class: 'pull-right' %>

		</div>
<% end %>

app/views/tags/new.html.erb
<h1>ADD A TAG</h1>

<%= bootstrap_form_for @tag do |t| %>
<%= t.text_area :name %>
<%= t.primary %>
<% end %>

app/views/tags/show.html.erb
<h2>#<%= @tag.name %></h2>

<% @tag.creatures.each do |creature| %>
<div class="well">
  <%= link_to creature.name, creature %>
</div>
<% end %>